version: "3.9"

services:
  backup_service:
    build:
      context: .
      dockerfile: Dockerfile.backup
    environment:
      AUTOMATIC_BACKUP: ${AUTOMATIC_BACKUP}
      BACKUP_DB_URL: ${BACKUP_DB_URL}
      BACKUP_DIR: ${BACKUP_DIR}
      ACCESS_KEY_ID: ${ACCESS_KEY_ID}
      SECRET_ACCESS_KEY: ${SECRET_ACCESS_KEY}
      ACCOUNT_ID: ${ACCOUNT_ID}
      BUCKET_NAME: ${BUCKET_NAME}
    volumes:
      - backups:/app/backups
    restart: always
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"

volumes:
  backups:
